---
execute: 
  echo: true
  eval: false
  warning: false
---

# Quantification of transcript abundances

In this chapter, you will learn how to generate transcript abundance files 
from FASTQ files using the [nf-core/rnaseq](https://nf-co.re/rnaseq/3.26.0/) Nextflow pipeline. At the end of this chapter, you will be able to:
- Understand the overall workflow of _nf-core/rnaseq_
- Adjust pipeline parameters for different types of RNA-seq datasets, 
including single- or paired-end sequencing data, and datasets with or 
without spike-in standards.

## Introduction to the _nf-core/rnaseq_ pipeline

The [nf-core/rnaseq](https://nf-co.re/rnaseq/3.26.0/) pipeline is a 
standardized bioinformatics pipeline built using Nextflow, a workflow 
management system designed to enable reproducible and scalable computational
analyses. The _nf-core/rnaseq_ pipeline provides an integrated workflow 
for processing RNA-seq data. The pipeline performs quality control (QC), 
trimming and alignment, and produces a gene expression matrix (i.e., 
transcript abundance files) and extensive QC report. 
[nf-core](https://nf-co.re/) is a global community collaborating to 
build open-source Nextflow components and pipelines [@ewels2020nf].

## Obtaining the example data set

Our example data set contains sequencing reads (FASTQ files) from 2
*Arabidopsis thaliana* genotypes, and three ploidy levels (2x, 4x, and
8x; see *Preface* for details). For the sake of demonstration, 
each example file contains only the first 5,000 reads from the 
corresponding original FASTQ file.
Let's download the example data from Zenodo and store them in a directory 
named `rnaseq_data` in the temporary directory (`/tmp/`). The `FASTQ_example` folder contains 25 example FASTQ files. 

```{bash}
# Download the `FASTQ_example` folder to `/tmp/rnaseq_data/`
mkdir -p /tmp/rnaseq_data

## `FASTQ_example/`
wget -O /tmp/rnaseq_data/FASTQ_example.zip \
  "https://zenodo.org/records/22938731/files/FASTQ_example.zip?download=1"
unzip /tmp/rnaseq_data/FASTQ_example.zip -d /tmp/rnaseq_data && rm /tmp/rnaseq_data/FASTQ_example.zip

## `nextflow_metadata.csv`
wget -O /tmp/rnaseq_data/nextflow_metadata.csv \
  "https://zenodo.org/records/22938731/files/nextflow_metadata.csv?download=1"
sed -i 's|/blue/soltis/shan158538/PI3_node-1/tutorial/fastq_files_download/|/tmp/rnaseq_data/FASTQ_example/|g' /tmp/rnaseq_data/nextflow_metadata.csv

## Reference genome (FASTA)
wget -O /tmp/rnaseq_data/Athaliana_TAIR10.fa.gz \
  "https://ftp.ensemblgenomes.ebi.ac.uk/pub/plants/release-63/fasta/arabidopsis_thaliana/dna/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa.gz"

## Reference annotation (GTF)
wget -O /tmp/rnaseq_data/Athaliana_TAIR10.gtf.gz \
  "https://ftp.ensemblgenomes.ebi.ac.uk/pub/plants/release-63/gtf/arabidopsis_thaliana/Arabidopsis_thaliana.TAIR10.63.gtf.gz"
  
## Sequences of spike-in standards (FASTA)
wget -O /tmp/rnaseq_data/ERCC92.zip \
  "https://assets.thermofisher.com/TFS-Assets/LSG/manuals/ERCC92.zip" && \
  unzip -j /tmp/rnaseq_data/ERCC92.zip ERCC92.fa -d /tmp/rnaseq_data && \
  rm /tmp/rnaseq_data/ERCC92.zip
```

After downloading all files, this is what the folder looks like:

```{bash}
$ tree /tmp/rnaseq_data/
#>/tmp/rnaseq_data/
#>├── Athaliana_TAIR10.fa.gz
#>├── Athaliana_TAIR10.gtf.gz
#>├── ERCC92.fa
#>├── FASTQ_example
#>│   ├── CMQCZ8_20_sample_20_first5000.fastq.gz
#>│   ├── CMQCZ8_21_sample_21_first5000.fastq.gz
#>│   ├── CMQCZ8_22_sample_22_first5000.fastq.gz
#>│   ├── CMQCZ8_23_sample_23_first5000.fastq.gz
#>│   ├── CMQCZ8_24_sample_24_first5000.fastq.gz
#>│   ├── CMQCZ8_25_sample_25_first5000.fastq.gz
#>│   ├── CMQCZ8_26_sample_26_first5000.fastq.gz
#>│   ├── CMQCZ8_27_sample_27_first5000.fastq.gz
#>│   ├── CMQCZ8_28_sample_28_first5000.fastq.gz
#>│   ├── CMQCZ8_29_sample_29_first5000.fastq.gz
#>│   ├── CMQCZ8_30_sample_30_first5000.fastq.gz
#>│   ├── CMQCZ8_31_sample_31_first5000.fastq.gz
#>│   ├── CMQCZ8_32_sample_32_first5000.fastq.gz
#>│   ├── CMQCZ8_33_sample_33_first5000.fastq.gz
#>│   ├── CMQCZ8_34_sample_34_first5000.fastq.gz
#>│   ├── CMQCZ8_45_sample_45_first5000.fastq.gz
#>│   ├── CMQCZ8_46_sample_46_first5000.fastq.gz
#>│   ├── CMQCZ8_47_sample_47_first5000.fastq.gz
#>│   ├── CMQCZ8_48_sample_48_first5000.fastq.gz
#>│   ├── CMQCZ8_49_sample_49_first5000.fastq.gz
#>│   ├── CMQCZ8_50_sample_50_first5000.fastq.gz
#>│   ├── CMQCZ8_51_sample_51_first5000.fastq.gz
#>│   ├── CMQCZ8_52_sample_52_first5000.fastq.gz
#>│   ├── CMQCZ8_53_sample_53_first5000.fastq.gz
#>│   └── CMQCZ8_54_sample_54_first5000.fastq.gz
#>└── nextflow_metadata.csv
#>
#>1 directory, 29 files
```

For the input samplesheet file (i.e., `nextflow_metadata.csv`), the first four columns must be `sample`, `fastq1`, `fastq2`, and `strandedness` (in this
exact order). The pipeline will auto-detect whether a sample is single- 
or paired-end using the information provided in the samplesheet. 
The strandedness column can be set to 'auto', allowing the pipeline to 
infer the library strandedness. Additional columns can be included in 
the samplesheet as needed, but the first four columns must follow the 
format and order described above.

This is what our samplesheet file looks like:

```{bash}
$ head /tmp/rnaseq_data/nextflow_metadata.csv 
#>sample,fastq_1,fastq_2,strandedness
#>C2x_rep1,/tmp/rnaseq_data/FASTQ_example/CMQCZ8_20_sample_20_first5000.fastq.gz,,auto
#>C2x_rep2,/tmp/rnaseq_data/FASTQ_example/CMQCZ8_21_sample_21_first5000.fastq.gz,,auto
#>C2x_rep3,/tmp/rnaseq_data/FASTQ_example/CMQCZ8_22_sample_22_first5000.fastq.gz,,auto
#>C2x_rep4,/tmp/rnaseq_data/FASTQ_example/CMQCZ8_23_sample_23_first5000.fastq.gz,,auto
#>C2x_rep5,/tmp/rnaseq_data/FASTQ_example/CMQCZ8_24_sample_24_first5000.fastq.gz,,auto
#>C4x_rep1,/tmp/rnaseq_data/FASTQ_example/CMQCZ8_25_sample_25_first5000.fastq.gz,,auto
#>C4x_rep2,/tmp/rnaseq_data/FASTQ_example/CMQCZ8_26_sample_26_first5000.fastq.gz,,auto
#>C4x_rep3,/tmp/rnaseq_data/FASTQ_example/CMQCZ8_27_sample_27_first5000.fastq.gz,,auto
#>C4x_rep4,/tmp/rnaseq_data/FASTQ_example/CMQCZ8_28_sample_28_first5000.fastq.gz,,auto
```

## Executing the pipeline

In our workflow, we run the pipeline to execute the following steps:
basic QC with _FastQC_ [@bioinformatics2011fastqc], read trimming with _fastp_ [@chen2018fastp], read mapping to the reference genome with 
_STAR_ [@dobin2013star], and transcript abundance quantification with
_salmon_ [@patro2017salmon]. For each of these steps, you can either 
go with default parameters,
or specify custom options in a `params.yml` file. Our `params.yml` looks
like this:

```{bash}
aligner: star_salmon
seq_platform: ILLUMINA
trimmer: fastp
with_umi: true
skip_umi_extract: true
umitools_umi_separator: "_"
extra_salmon_quant_args: "--noLengthCorrection"
```

Of note, we're using `--noLengthCorrection` in _salmon_ because
our data were generated with 3' tagged RNA-seq data, so no 
differences in transcript length should be taken into account.
To execute the pipeline on a SLURM cluster, you'd run the following script:

```{bash}
#!/bin/bash
#SBATCH --job-name=nextflow-rnaseq_v1
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=your_email_address
#SBATCH --time=1-00:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH --mem=120GB
#SBATCH --qos=your_group

module purge
module load nf-core nextflow singularity

CSV=/tmp/rnaseq_data/nextflow_metadata.csv
GENOME=/tmp/rnaseq_data/Athaliana_TAIR10.fa.gz
GTF=/tmp/rnaseq_data/Athaliana_TAIR10.gtf.gz
SPIKEIN=/tmp/rnaseq_data/ERCC92.fa
PARAMS=params.yml

nextflow run nf-core/rnaseq \
  -r 3.26.0 \
  -profile singularity \
  -params-file ${PARAMS} \
  --input ${CSV} \
  --outdir . \
  --gtf ${GTF} \
  --fasta ${GENOME} \
  --additional_fasta ${SPIKEIN}
```


If you're using your lab's own server instead of a SLURM cluster, remove 
the lines containing '#SBATCH' and `module load` calls. After executing
the pipeline, you should be able to see `star_salmon` folder in its output
directory. This is where you will find all transcript abundance estimations
we will use in other chapters. Importing such quantifications to a final matrix
of gene-level transcript abundances is the topic of the next chapter.


## Session info {.unnumbered}

This document was created under the following conditions:

```{r sessioninfo}
#| eval: true
#| echo: false
sessioninfo::session_info()
```

## References {.unnumbered}
